### ISSUE TITLE
Colors in terminal

### ISSUE THREAD

**Issue by artem00971** [mswift42/foggy-night-theme#1]
When I use ls command names of directories which have sticky bit enabled such as /tmp are unreadable because text foreground color matches text background color.

**Comment by mswift42** [comment]
Could you post a screenshot, please ?

**Comment by artem00971** [comment]
![2019-01-21-194418_1920x1080_scrot](https://user-images.githubusercontent.com/46899632/51491106-03695980-1db6-11e9-83c9-ef791f336a35.png)

**Comment by mswift42** [comment]
Thanks, I'll have a look at it  tomorrow.

**Comment by mswift42** [comment]
I've just updated the color for `term-color-black.` 

Please check after next melpa update if this is fixed for you.

Thanks.

**Comment by artem00971** [comment]
Now it is fine
![2019-01-23-185508_1920x1080_scrot](https://user-images.githubusercontent.com/46899632/51623200-da290480-1f40-11e9-88c4-a7ea4924b034.png)
